package calculadora_1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author david
 */
public class calculadora extends javax.swing.JFrame {

    
    // variables donde se guardan los numero para las operaciones
    int num_1, num_2;
    // sirve para elegir las operaciones
    String signo;
    

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton24 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JLabel();
        Boton_Borrar = new javax.swing.JButton();
        Boton_8 = new javax.swing.JButton();
        Boton_9 = new javax.swing.JButton();
        Boton_Division = new javax.swing.JButton();
        Boton_7 = new javax.swing.JButton();
        Boton_5 = new javax.swing.JButton();
        Boton_6 = new javax.swing.JButton();
        Boton_Multiplicacion = new javax.swing.JButton();
        Boton_4 = new javax.swing.JButton();
        Boton_2 = new javax.swing.JButton();
        Boton_3 = new javax.swing.JButton();
        Boton_Resta = new javax.swing.JButton();
        Boton_1 = new javax.swing.JButton();
        Boton_Suma = new javax.swing.JButton();
        Boton_0 = new javax.swing.JButton();
        Boton_Igual = new javax.swing.JButton();

        jButton24.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel.setOpaque(true);

        Boton_Borrar.setText("C");
        Boton_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BorrarActionPerformed(evt);
            }
        });

        Boton_8.setText("8");
        Boton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_8ActionPerformed(evt);
            }
        });

        Boton_9.setText("9");
        Boton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_9ActionPerformed(evt);
            }
        });

        Boton_Division.setText("/");
        Boton_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_DivisionActionPerformed(evt);
            }
        });

        Boton_7.setText("7");
        Boton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_7ActionPerformed(evt);
            }
        });

        Boton_5.setText("5");
        Boton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_5ActionPerformed(evt);
            }
        });

        Boton_6.setText("6");
        Boton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_6ActionPerformed(evt);
            }
        });

        Boton_Multiplicacion.setText("*");
        Boton_Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_MultiplicacionActionPerformed(evt);
            }
        });

        Boton_4.setText("4");
        Boton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_4ActionPerformed(evt);
            }
        });

        Boton_2.setText("2");
        Boton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_2ActionPerformed(evt);
            }
        });

        Boton_3.setText("3");
        Boton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_3ActionPerformed(evt);
            }
        });

        Boton_Resta.setText("-");
        Boton_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_RestaActionPerformed(evt);
            }
        });

        Boton_1.setText("1");
        Boton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_1ActionPerformed(evt);
            }
        });

        Boton_Suma.setText("+");
        Boton_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SumaActionPerformed(evt);
            }
        });

        Boton_0.setText("0");
        Boton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_0ActionPerformed(evt);
            }
        });

        Boton_Igual.setText("=");
        Boton_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_IgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Boton_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Boton_9, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(Boton_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Boton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Boton_2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Boton_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Boton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Boton_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Boton_8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(Boton_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Boton_Division, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Boton_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Boton_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton_8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Boton_Suma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Boton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_9ActionPerformed
        //Mostrar numero 9 en pantalla
        panel.setText(panel.getText() + "9");

    }//GEN-LAST:event_Boton_9ActionPerformed

    private void Boton_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_DivisionActionPerformed
        // agarra el numero en pantalla para guardarlo en la variable num_1
        num_1 = Integer.parseInt(panel.getText());
        signo = "/";
        // borra lo mostrado en pantalla
        panel.setText("");
    }//GEN-LAST:event_Boton_DivisionActionPerformed

    private void Boton_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BorrarActionPerformed
        // limpia el los numeros del panel
        panel.setText("");
    }//GEN-LAST:event_Boton_BorrarActionPerformed

    private void Boton_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_IgualActionPerformed

        // agarra el ultimo numero de la pantalla para hacer las operaciones
        num_2 = Integer.parseInt(panel.getText());

        // hace las operaciones segun el signo elegido
        switch (signo) {
            case "+":
                // hace la suma y la muestra en el pantalla
                panel.setText(Integer.toString(num_1 + num_2));
                break;
            case "-":
                // hace la resta y la muestra en pantalla
                panel.setText(Integer.toString(num_1 - num_2));
                break;
            case "*":
                // hace la multiplicacion y la muestra en la pantalla 
                panel.setText(Integer.toString(num_1 * num_2));
                break;
            case "/":
                // hace la divicion y la muestra en pantallla
                // pregunta si el segundo numero es 0 
                if(num_2 != 0){ 
                   panel.setText(Integer.toString(num_1 / num_2)); 
                }else{
                  panel.setText("error: divicion por cero");
                }
               break;

        }
    }//GEN-LAST:event_Boton_IgualActionPerformed

    private void Boton_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SumaActionPerformed
        // agarra el numero en pantalla para guardarlo en la variable num_1
        num_1 = Integer.parseInt(panel.getText());
        signo = "+";
        // borra lo mostrado en bantalla
        panel.setText("");
    }//GEN-LAST:event_Boton_SumaActionPerformed

    private void Boton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_2ActionPerformed
       // muestra el numero 2 en pantalla
        panel.setText(panel.getText() + "2");
    }//GEN-LAST:event_Boton_2ActionPerformed

    private void Boton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_0ActionPerformed
        // muestra el numero 0 en pantalla
        panel.setText(panel.getText() + "0");
    }//GEN-LAST:event_Boton_0ActionPerformed

    private void Boton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_1ActionPerformed
        //muestra el numero 1 en pantalla
        panel.setText(panel.getText() + "1");
    }//GEN-LAST:event_Boton_1ActionPerformed

    private void Boton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_3ActionPerformed
        // muestra el numero 3 en pantalla
        panel.setText(panel.getText() + "3");
    }//GEN-LAST:event_Boton_3ActionPerformed

    private void Boton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_4ActionPerformed
        // muestra el numero 4 en pantalla
        panel.setText(panel.getText() + "4");
    }//GEN-LAST:event_Boton_4ActionPerformed

    private void Boton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_5ActionPerformed
        // muestra el numero 5 en pantalla
        panel.setText(panel.getText() + "5");
    }//GEN-LAST:event_Boton_5ActionPerformed

    private void Boton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_6ActionPerformed
       // muestra el numero 6 en pantalla
        panel.setText(panel.getText() + "6");
    }//GEN-LAST:event_Boton_6ActionPerformed

    private void Boton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_7ActionPerformed
        // muestra el numero 7 en el panel
        panel.setText(panel.getText() + "7");
    }//GEN-LAST:event_Boton_7ActionPerformed

    private void Boton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_8ActionPerformed
        // muestra el numero 8 en pantalla
        panel.setText(panel.getText() + "8");
    }//GEN-LAST:event_Boton_8ActionPerformed

    private void Boton_MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_MultiplicacionActionPerformed

        // agarra el numero mostrado en pantalla para guardarlo en la variable num_1
        num_1 = Integer.parseInt(panel.getText());
        signo = "*";
        // borra lo mostrado en pantalla
        panel.setText("");
    }//GEN-LAST:event_Boton_MultiplicacionActionPerformed

    private void Boton_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RestaActionPerformed
        //agarra el el primer numero mostrado en patalla y lo guarda en la variable num_1
        num_1 = Integer.parseInt(panel.getText());
        signo = "-";
        // borra lo mostrado en pantalla
        panel.setText("");
    }//GEN-LAST:event_Boton_RestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new calculadora().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_0;
    private javax.swing.JButton Boton_1;
    private javax.swing.JButton Boton_2;
    private javax.swing.JButton Boton_3;
    private javax.swing.JButton Boton_4;
    private javax.swing.JButton Boton_5;
    private javax.swing.JButton Boton_6;
    private javax.swing.JButton Boton_7;
    private javax.swing.JButton Boton_8;
    private javax.swing.JButton Boton_9;
    private javax.swing.JButton Boton_Borrar;
    private javax.swing.JButton Boton_Division;
    private javax.swing.JButton Boton_Igual;
    private javax.swing.JButton Boton_Multiplicacion;
    private javax.swing.JButton Boton_Resta;
    private javax.swing.JButton Boton_Suma;
    private javax.swing.JButton jButton24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel panel;
    // End of variables declaration//GEN-END:variables
}
